feat: --stop-signal-file for cifuzz execute
CodeIntelligenceTesting/cifuzz pull request #1026
Opened 2023-09-01 10:02 UTC by mlsandnerCI

### Motivation/Context

> When executing fuzz containers in a k8s setup we need to signal to sidecar containers that the main process has finished to stop any sidecar containers running alongside the main cifuzz execution.

### Description
`cifuzz execute` now has a boolean flag `--stop-signal-file` that if set, creates an empty file called `cifuzz-execution-finished` on exit.

### How to use/reproduce
- create bundle e.g. for maven 
- run cifuzz execute in unzipped bundle with `--stop-signal-file`

2023-09-05 09:49 UTC, jochil commented
Can we add the flag already to the default `cifuzz execute` call? Or is there a reason against it?

2023-09-05 09:52 UTC, jochil commented on internal/cmd/execute/execute.go
> +	cmd.Flags().Bool("stop-signal-file", false, "CI Fuzz will create a file 'cifuzz-execution-finished' upon exit")
In the jira task it was defined as `--stop-signal-file=<filename>` not just a boolean flag... did this requirement changed somehow?

2023-09-05 09:52 UTC, jochil commented on internal/cmd/execute/execute.go
> +				defer func() {
I think we should cover the creation of the stop file with a small test

2023-09-05 11:16 UTC, adombeck requested changes
Citing https://code-intelligence.atlassian.net/browse/CLI-1235:
> The specified file should be written on exit of the cifuzz command and contain information if cifuzz exited with an error or as expected (e.g. write the exit code into the file). 

AFAICT the file that's written here does not tell the user anything about the exit status.

2023-09-05 14:06 UTC, adombeck commented
> Citing https://code-intelligence.atlassian.net/browse/CLI-1235:
> 
> > The specified file should be written on exit of the cifuzz command and contain information if cifuzz exited with an error or as expected (e.g. write the exit code into the file).
> 
> AFAICT the file that's written here does not tell the user anything about the exit status.

@simonresch clarified out of band that the backend team does not need the file to include the exit status.

2023-09-07 11:04 UTC, mlsandnerCI commented on internal/cmd/execute/execute.go
> +	cmd.Flags().Bool("stop-signal-file", false, "CI Fuzz will create a file 'cifuzz-execution-finished' upon exit")
As discussed in the planning, right now there is no reason for the filename to be configurable so it should be fine to keep it simple for now

2023-09-07 11:07 UTC, mlsandnerCI commented
> Can we add the flag already to the default `cifuzz execute` call? Or is there a reason against it?

You mean including it in the container run command where we call execute? I don't know if every user needs this file but of course it could be added 🤔

2023-09-07 11:23 UTC, mlsandnerCI commented on internal/cmd/execute/execute.go
> +				defer func() {
I created a very simple test that calls the command with the flag and checks if the file has been created, no matter if the command succeeded or not. Is this okay?

2023-09-07 11:59 UTC, jochil commented on internal/cmd/execute/execute.go
> +				defer func() {
works for me. thanks

2023-09-07 12:01 UTC, jochil commented
> > Can we add the flag already to the default `cifuzz execute` call? Or is there a reason against it?
> 
> You mean including it in the container run command where we call execute? I don't know if every user needs this file but of course it could be added 🤔

I mean if the file is there it creates no harm but the backend team don't have to take care of the flag

2023-09-07 12:34 UTC, mlsandnerCI commented
> > > Can we add the flag already to the default `cifuzz execute` call? Or is there a reason against it?
> > 
> > 
> > You mean including it in the container run command where we call execute? I don't know if every user needs this file but of course it could be added 🤔
> 
> I mean if the file is there it creates no harm but the backend team don't have to take care of the flag

True but would we need the flag then at all? Then it could just be part of the regular execute workflow.

2023-09-07 12:38 UTC, jochil commented
> > > > Can we add the flag already to the default `cifuzz execute` call? Or is there a reason against it?
> > > 
> > > 
> > > You mean including it in the container run command where we call execute? I don't know if every user needs this file but of course it could be added 🤔
> > 
> > 
> > I mean if the file is there it creates no harm but the backend team don't have to take care of the flag
> 
> True but would we need the flag then at all? Then it could just be part of the regular execute workflow.

Good question... @simonresch @adombeck WDYT?

2023-09-07 14:57 UTC, simonresch commented
> > > > > Can we add the flag already to the default `cifuzz execute` call? Or is there a reason against it?
> > > > 
> > > > 
> > > > You mean including it in the container run command where we call execute? I don't know if every user needs this file but of course it could be added 🤔
> > > 
> > > 
> > > I mean if the file is there it creates no harm but the backend team don't have to take care of the flag
> > 
> > 
> > True but would we need the flag then at all? Then it could just be part of the regular execute workflow.
> 
> Good question... @simonresch @adombeck WDYT?

Setting the flag in the backend is not a problem. We would like to control where the file is saved anyways to make that uniform with the behavior of `fuzzer-runner` calls.

2023-09-08 08:27 UTC, simonresch commented
> > Setting the flag in the backend is not a problem. We would like to control where the file is saved anyways to make that uniform with the behavior of `fuzzer-runner` calls.
> 
> Does that mean you do need the flag to be configurable, so a string instead of boolean? @simonresch

A string flag where we can pass the file name would be ideal. We can't be sure that the directory where cifuzz is executed is writable in the k8s pod. Making this configurable would help there.

2023-09-08 08:37 UTC, mlsandnerCI commented
> > > Setting the flag in the backend is not a problem. We would like to control where the file is saved anyways to make that uniform with the behavior of `fuzzer-runner` calls.
> > 
> > 
> > Does that mean you do need the flag to be configurable, so a string instead of boolean? @simonresch
> 
> A string flag where we can pass the file name would be ideal. We can't be sure that the directory where cifuzz is executed is writable in the k8s pod. Making this configurable would help there.

Alright, then I will change it 👍

2023-09-08 10:00 UTC, jochil approved these changes

2023-09-08 11:17 UTC, merged