feat(container): send POST to CI Sense for container remote run
CodeIntelligenceTesting/cifuzz pull request #1054
Opened 2023-09-12 09:43 UTC by MarkusZoppelt

### Motivation/Context

The `/v3/runs` endpoint in CI Sense expects us to POST a container remote run.

### Description

* add API structs and func to communicate with the `v3/runs` endpoint
* send request after container build during `cifuzz container remote-run`

### How to use/reproduce

Ensure you are logged in to CI Sense:

    cifuzz login --server app.staging.code-intelligence.com

build this branch and the corresponding container image:

    make install
    make build-container-image

Start a local container registry for testing:

    docker run -d -p 5000:5000 --name cifuzz-test-registry registry:2

Try container remote run and see the successfull POST in `verbose` mode:

    cifuzz container remote-run -C examples/maven --registry localhost:5000/test/cifuzz  com.example.FuzzTestCase::myFuzzTest --server app.staging.code-intelligence.com -v

2023-09-14 19:10 UTC, jochil requested changes
Great instructions for reproducing it, thanks!
But I got the following error:
```
🔍 POST container remote run to https://app.staging.code-intelligence.com: {"image":"localhost:5000/test/cifuzz:b13844d9f886a97da753106e058e34ba41b2b7d3e0e47947a12d4b83ad0072b3","fuzz_tests":[{"name":"com.example.FuzzTestCase::myFuzzTest"}],"project_external_id":"Foo%20Bar-5ce01809"}
❌ 400 Bad Request: No such project
```
I tried other projects and depending on the project name the result changed. So every time there is a white space the project name I got a `400` response.
```
Foo Bar -> 400
Test123 -> 200
Android Example -> 400
Test1 -> 200
```
Can you check this please? Maybe the API expects the name in the json body to be not url encoded?

2023-09-14 19:10 UTC, jochil commented on e2e/docker.go
> +		testCaseRun.args = "--server=" + server + " " + testCaseRun.args
just a thought.. maybe using `fmt.Sprintf` here?

2023-09-15 08:10 UTC, MarkusZoppelt commented on internal/api/container_run.go
> +	log.Debugf("POST container remote run to %s: %s\n", client.Server, string(body))
I like the idea. Should I leave it as is and wait for your incoming changes?

2023-09-15 08:11 UTC, MarkusZoppelt commented on internal/api/container_run.go
> +	body, err := json.Marshal(containerRun)
Cool idea. I would like to keep the concise output for our `--plain` style output and your proposed solution for `--pretty` (default).

2023-09-15 08:34 UTC, MarkusZoppelt commented on internal/api/container_run.go
I will replace all custom `Types` with `*Types`

2023-09-15 09:15 UTC, MarkusZoppelt commented on internal/cmd/container/remoterun/remoterun.go
> +func (c *containerRemoteRunCmd) selectProject(projects []*api.Project) (string, error) {
I introduced two new functions in the `dialog` package that are reusable 👍🏼

2023-09-15 09:15 UTC, MarkusZoppelt commented on internal/api/container_run.go
Done

2023-09-15 09:34 UTC, MarkusZoppelt commented on internal/api/container_run.go
> +	body, err := json.Marshal(containerRun)
And maybe in another PR. This one is already changing a bunch of files in different places. Will create a ticket.

2023-09-15 09:40 UTC, MarkusZoppelt commented on internal/api/container_run.go
> +	body, err := json.Marshal(containerRun)
CLI-1280

2023-09-15 11:53 UTC, jochil approved these changes
thanks

2023-09-15 12:11 UTC, merged