store crashing input to `.cifuzz-findings`
CodeIntelligenceTesting/cifuzz pull request #144
Opened 2022-07-14 13:05 UTC by jochil

2022-07-14 15:35 UTC, jochil commented on internal/moby/namesgenerator/names-generator.go
> +// Package namesgenerator generates random names.
do you think it is sufficient to add the copyright notice to the top of the files (as it also mentions the license)?

2022-07-14 15:45 UTC, adombeck commented on internal/moby/namesgenerator/names-generator.go
> +// Package namesgenerator generates random names.
I think I would just copy the `NOTICE` and `LICENSE` files into the `moby` directory

2022-07-14 15:57 UTC, jochil commented on internal/moby/namesgenerator/names-generator.go
> +func GetDeterminsticName(seed []byte) string {
done

2022-07-14 16:03 UTC, adombeck commented on pkg/report/finding.go
> +	if f.InputFile != "" {
I would move that check to the `Save` function, i.e. only call `moveInputFile` if `f.InputFile != ""`.

2022-07-14 16:07 UTC, jochil commented on pkg/report/finding.go
> +	Name               string        `json:"name,omitempty"`
it get set in the `report_handler`

2022-07-14 16:13 UTC, jochil commented on pkg/report/finding.go
> +	if f.InputFile != "" {
done

2022-07-14 16:13 UTC, jochil commented on pkg/report/finding.go
> +		// because of minijail we can not use os.Rename for moving the file
done

2022-07-14 16:17 UTC, adombeck commented on pkg/report/finding.go
> +	Name               string        `json:"name,omitempty"`
Strange, `intellij` doesn't show that reference

2022-07-14 16:21 UTC, jochil commented on pkg/report/finding.go
> +	bytes, err := prettyjson.Marshal(f)
ups... done

2022-07-14 16:40 UTC, adombeck commented
>  feat(names): add function for determinstic name generation 

The commit message contains the same typo as the function name

2022-07-14 16:41 UTC, adombeck approved these changes

2022-07-14 17:25 UTC, fmeum requested changes

2022-07-14 17:25 UTC, fmeum commented on internal/moby/namesgenerator/names-generator.go
> +	if len(seed) < 8 {
I would feel more comfortable if we used https://pkg.go.dev/crypto/sha256#Sum256 to properly hash the seed and then use the hash to feed the RNG. That should avoid collisions very well. With the current scheme, it looks to me like only the first 8 bytes of the seed are used.

2022-07-14 18:27 UTC, adombeck commented
> I may be out of the loop, but why do we have to vendor the name generator?

I suggested this to avoid pulling in all of docker as a dependency just to be able to use this small package.

2022-07-15 07:59 UTC, jochil commented on util/testutil/testutil.go
> +func PrepareTestTempDir(prefix string) string {
good point. done

2022-07-15 08:35 UTC, jochil commented on internal/moby/namesgenerator/names-generator.go
> +	if len(seed) < 8 {
> Seed values that have the same remainder when divided by 2³¹-1 generate the same pseudo-random sequence.

This is what the go docs say about that. I don't see how using a hash should reduce the **probability** of a (natural) collision... yes, it would be harder to produce one by intent, but this is not a problem in our scenario.

And in our case the seed is already a hash generated from the crashing input

> With the current scheme, it looks to me like only the first 8 bytes of the seed are used.

Thats correct, but because the `Source` takes an `int64`. I did not find a way to get around this... and to be honest I am not sure if this is even necessary.

2022-07-15 08:51 UTC, adombeck approved these changes

2022-07-15 09:14 UTC, fmeum commented on internal/moby/namesgenerator/names-generator.go
> +	if len(seed) < 8 {
> And in our case the seed is already a hash generated from the crashing input

If that's the case, then my comment was misguided. I expected `seed []byte` to be the *contents* of a seed file, which aren't pseudo-random. But I now see that you are already passing a hash into the function - may I request we rename the parameter to `hash` or `digest`?

2022-07-15 09:21 UTC, fmeum commented
> > I may be out of the loop, but why do we have to vendor the name generator?
> 
> I suggested this to avoid pulling in all of docker as a dependency just to be able to use this small package.

This should no longer be an issue with Go 1.18, which loads modules lazily and prunes the module graph to include only the modules transitively required to build the current main module.

I just did `go get github.com/docker/docker` and then used the `namesgenerator` package somewhere. I didn't experience any slowness and the diff is very manageable:

```
diff --git a/go.mod b/go.mod
index ae6af6a..7470ff2 100644
--- a/go.mod
+++ b/go.mod
@@ -23,6 +23,7 @@ require (
 	github.com/containerd/console v1.0.3 // indirect
 	github.com/cpuguy83/go-md2man/v2 v2.0.2 // indirect
 	github.com/davecgh/go-spew v1.1.1 // indirect
+	github.com/docker/docker v20.10.17+incompatible // indirect
 	github.com/lithammer/fuzzysearch v1.1.5 // indirect
 	github.com/mattn/go-colorable v0.1.12 // indirect
 	github.com/mattn/go-isatty v0.0.14 // indirect
diff --git a/go.sum b/go.sum
index 0e5b948..dcb055e 100644
--- a/go.sum
+++ b/go.sum
@@ -69,6 +69,8 @@ github.com/cpuguy83/go-md2man/v2 v2.0.2/go.mod h1:tgQtvFlXSQOSOSIRvRPT7W67SCa46t
 github.com/davecgh/go-spew v1.1.0/go.mod h1:J7Y8YcW2NihsgmVo/mv3lAwl/skON4iLHjSsI+c5H38=
 github.com/davecgh/go-spew v1.1.1 h1:vj9j/u1bqnvCEfJOwUhtlOARqs3+rkHYY13jYWTU97c=
 github.com/davecgh/go-spew v1.1.1/go.mod h1:J7Y8YcW2NihsgmVo/mv3lAwl/skON4iLHjSsI+c5H38=
+github.com/docker/docker v20.10.17+incompatible h1:JYCuMrWaVNophQTOrMMoSwudOVEfcegoZZrleKc1xwE=
+github.com/docker/docker v20.10.17+incompatible/go.mod h1:eEKB0N0r5NX/I1kEveEz05bcu8tLC/8azJZsviup8Sk=
 github.com/envoyproxy/go-control-plane v0.9.0/go.mod h1:YTl/9mNaCwkRvm6d1a2C3ymFceY/DCBVvsKhRF0iEA4=
 github.com/envoyproxy/go-control-plane v0.9.1-0.20191026205805-5f8ba28d4473/go.mod h1:YTl/9mNaCwkRvm6d1a2C3ymFceY/DCBVvsKhRF0iEA4=
 github.com/envoyproxy/go-control-plane v0.9.4/go.mod h1:6rpuAdCZL397s3pYoYcLgu1mIlRU8Am5FuJP05cCM98=
diff --git a/internal/cmd/create/create.go b/internal/cmd/create/create.go
index d267d24..35a599a 100644
--- a/internal/cmd/create/create.go
+++ b/internal/cmd/create/create.go
@@ -6,6 +6,7 @@ import (
 	"path/filepath"
 	"strings"
 
+	"github.com/docker/docker/pkg/namesgenerator"
 	"github.com/spf13/cobra"
 	"golang.org/x/exp/maps"
 
@@ -48,6 +49,7 @@ func New(config *config.Config) *cobra.Command {
 }
 
 func run(cmd *cobra.Command, args []string, opts *cmdOpts) (err error) {
+	namesgenerator.GetRandomName(5)
 	// get test type
 	opts.testType, err = getTestType(args, cmd.InOrStdin())
 	if err != nil {
```

Unless you see any other potential issues with this, I would prefer not to vendor.

2022-07-15 09:21 UTC, jochil commented on internal/moby/namesgenerator/names-generator.go
> +	if len(seed) < 8 {
I first named the parameter `hash` but I found it a bit misleading. For me `seed` indicates that if I give in the same parameter value I will get the same result... imo it is a seed. Maybe another name with the same semantic meaning or adding a comment making it clear?

2022-07-15 09:23 UTC, fmeum commented on internal/moby/namesgenerator/names-generator.go
> +	if len(seed) < 8 {
Yes, I can see why you would prefer `seed` in this context, it's just unfortunate that the term is overloaded in the context of fuzzing. But as I said above, having a comment that states the expected properties of `seed` as well as the fact that only the first 8 bytes of it are used would be sufficient IMO.

2022-07-15 09:28 UTC, adombeck commented
> Unless you see any other potential issues with this, I would prefer not to vendor.

Ok I'm fine with that

2022-07-15 09:34 UTC, jochil commented on internal/moby/namesgenerator/names-generator.go
> +	if len(seed) < 8 {
I will add a comment but names are important ;) what's about `init`, `unique`, `ident`, `initValue`, `base`

2022-07-15 09:35 UTC, fmeum commented
> I thought the same first but now I added functionality to the package and unfortunately the name lists from the package are not public. And the only accessible method will not fulfill our requirements of having the same name for the same crashing input (if this is still a requirement). I can work around this with //go:linkname but it is a tradeoff

If all it takes is `//go:linkname` and `import _ "unsafe"`, I would actually prefer that to vendoring. But I can understand if any of you don't.

2022-07-15 11:20 UTC, jochil commented on internal/moby/namesgenerator/names-generator.go
> +	if len(seed) < 8 {
done

2022-07-15 11:21 UTC, jochil commented
> If all it takes is `//go:linkname` and `import _ "unsafe"`, I would actually prefer that to vendoring. But I can understand if any of you don't.

I tried and it looks okay for me... what do you think @fmeum ?

2022-07-15 11:29 UTC, fmeum commented
> > If all it takes is `//go:linkname` and `import _ "unsafe"`, I would actually prefer that to vendoring. But I can understand if any of you don't.
> 
> I tried and it looks okay for me... what do you think @fmeum ?

Looks good to me, @adombeck, are you fine with this hack as well?

2022-07-15 11:30 UTC, fmeum approved these changes

2022-07-15 11:43 UTC, adombeck commented
> Looks good to me, @adombeck, are you fine with this hack as well?

Yes, works for me

2022-07-15 11:51 UTC, merged