Don't recover from UBSan findings by default
CodeIntelligenceTesting/cifuzz pull request #355
Opened 2022-10-07 09:34 UTC by adombeck

2022-10-07 10:20 UTC, fmeum commented on tools/cmake/cifuzz/cmake/cifuzz-functions.cmake
> +        if(CIFUZZ_RECOVER_UBSAN)
Do we really need both a compile-time and a runtime switch? The compile-time switch is problematic as CMake variables are cached per build directory, meaning that the new bit would need to be "hashed" into the build directory name.

2022-10-07 10:20 UTC, fmeum commented on integration-tests/cmake/testdata/src/parser/parser.cpp
> +      n <<= 32;
This may not be very reliable as the compile can easily tell it's UB and optimize accordingly. I have seen `__attribute__((optnone))` in this context, we could add it here as well.

2022-10-11 11:13 UTC, adombeck commented on internal/build/other/other.go
> +		// Don't recover from UBSan findings, else no crashing input is
Done in this commit, but same as this comment here it's removed again by the commit which introduces the `--recover-ubsan` option, which already explains the behavior in the flag's usage message.

2022-10-11 11:21 UTC, adombeck commented on internal/build/other/other.go
> +			"-fno-sanitize-recover=address",
Yes, good catch! But now that I'm thinking about it again, I wonder if this change could break current use cases of our users. IIRC, @pnoltof tried to set `ASAN_OPTIONS=halt_on_error=0` to recover from ASan findings - which is not something we officially support and I expect the UX to be pretty bad (with the same findings being reported over and over again), but maybe there is still some value in it? @pnoltof: Is this something you're currently using?

2022-10-11 11:28 UTC, adombeck commented on internal/cmdutils/pflag.go
> +		"Recover from findings of the undefined behavior sanitizer and continue fuzzing.\n"+
fixed

2022-10-11 11:48 UTC, adombeck commented on tools/cmake/cifuzz/cmake/cifuzz-functions.cmake
> +        if(CIFUZZ_RECOVER_UBSAN)
I don't know if there is any difference in the behavior of ASan with (1) `-fsanitize-recover=address` and `ASAN_OPTIONS=halt_on_error=1` and (2) `-fno-sanitize-recover=address`. We could go with (1) by default and only set the runtime option, `ASAN_OPTIONS=halt_on_error=0` when the `--recover-ubsan` flag is used.

2022-10-11 11:52 UTC, fmeum commented on internal/build/other/other.go
> +			"-fno-sanitize-recover=address",
We could emit a warning if we see `halt_on_error=0` in options, but I would say that using such an option is pretty clearly beyond any "stable API contract" users could reasonably expect.

2022-10-11 11:55 UTC, fmeum commented on tools/cmake/cifuzz/cmake/cifuzz-functions.cmake
> +        if(CIFUZZ_RECOVER_UBSAN)
Me neither. It's possible that `-fsanitize-recover=address` introduces runtime overhead, so we might want to check the LLVM sources for that. 

Not having conditional instrumentation flags would make this part of the code much simpler. In case we really do need different flags, I would rather introduce a new `asan-recoverable` sanitizer - this will play nicely with the cifuzz-CMake API contract we have settled on and lead to distinct build directories without further logic.

2022-10-11 15:21 UTC, jochil requested changes
If we change the default behavior we also have to check the tests in the pipelines.
These pipelines explicitly expect two findings on mac and linux for the example projects:
```
.github/workflows/pipeline_min_requirements.yml
.github/workflows/pipeline_e2e_installer.yml
.github/workflows/pipeline_e2e_source.yml
```
And the compatibility check here `.github/actions/compatibility_check/action.yml` expect that a new release produces the same findings as the previous one

I think I would prefer using the `recover-ubsan` in the examples projects instead of adjusting the tests.

We should also update the READMEs of the example projects so the user is aware of this... as, with this change, the "interessting" heap buffer overflow in the last branch of the example source code is not covered anymore

2022-10-11 16:15 UTC, adombeck commented on tools/cmake/cifuzz/cmake/cifuzz-functions.cmake
> +        if(CIFUZZ_RECOVER_UBSAN)
I spent some time looking through the LLVM sources, but I was not able to determine whether the `-fsanitize-recover` flag introduces significant runtime overhead. It does introduce checks in the instrumented code, for example [here](https://github.com/llvm/llvm-project/blob/df487bc425101c2550261db705f24f446967c6a7/llvm/lib/Transforms/Instrumentation/AddressSanitizer.cpp#L1632), but I can't tell if the runtime overhead of that is significant.

To get some rough idea, I ran our libfuzzer-runner tests a few times with `-fsanitize-recover=address` and a few times with `-fno-sanitize-recover=address`. The results are similar:
* recover: average CPU time: `13.27s` (min: `13.18`, max: `13.33`)
* no-recover: average CPU time: `13.39s` (min: `13.06`, max: `13.75`)

So I'm leaning towards always using `-fsanitize-recover=address` and only switching the runtime option. WDYT?

2022-10-11 16:50 UTC, fmeum commented on tools/cmake/cifuzz/cmake/cifuzz-functions.cmake
> +        if(CIFUZZ_RECOVER_UBSAN)
I don't understand the details of the codegen, but there doesn't seem to be anything that should be unreasonably slow in this case. Backed up by the measurement, I would say go for it.

2022-10-11 20:17 UTC, adombeck commented on tools/cmake/cifuzz/cmake/cifuzz-functions.cmake
> +        if(CIFUZZ_RECOVER_UBSAN)
done

2022-10-11 20:18 UTC, adombeck commented on integration-tests/cmake/testdata/src/parser/parser.cpp
> +      n <<= 32;
done

2022-10-11 20:18 UTC, adombeck commented
> I think I would prefer using the recover-ubsan in the examples projects instead of adjusting the tests.

done

2022-10-11 20:24 UTC, adombeck commented
> We should also update the READMEs of the example projects so the user is aware of this... as, with this change, the "interessting" heap buffer overflow in the last branch of the example source code is not covered anymore

done

2022-10-11 20:32 UTC, adombeck commented on internal/build/other/other.go
> +			"-fno-sanitize-recover=address",
The outcome of [this discussion](https://github.com/CodeIntelligenceTesting/cifuzz/pull/355#discussion_r989920133) was that we don't want to use the compile-time switch, so the behavior doesn't change - setting `ASAN_OPTIONS=halt_on_error=0` will work as before (i.e. still unsupported and untested but might still do something useful for some use cases). I agree that users can't have any reasonable expectations for options they set via `ASAN_OPTIONS` to work, so I don't think we need print a warning.

2022-10-11 22:54 UTC, adombeck commented on integration-tests/cmake/testdata/src/parser/parser.cpp
> +      n <<= 32;
that's causing errors on Windows: https://github.com/CodeIntelligenceTesting/cifuzz/actions/runs/3230350656/jobs/5288700407#step:5:167

I'll revert it

2022-10-12 00:12 UTC, adombeck commented on integration-tests/cmake/testdata/src/parser/parser.cpp
> +      n <<= 32;
Seems like MSVC does actually optimize this, because the undefined behavior is not reported. I'm trying to disable optimization for MSVC as well..

2022-10-12 08:42 UTC, jochil commented on examples/other/cifuzz.yaml
> +#build-command: "make my_fuzz_test"
my commenting out `build-command`? Shouldn't it be `build-command: make clean && make $FUZZ_TEST`?

2022-10-12 09:13 UTC, adombeck commented on integration-tests/cmake/testdata/src/parser/parser.cpp
> +      n <<= 32;
nevermind, forgot that MSVC doesn't support UBSan

2022-10-12 10:25 UTC, adombeck commented on examples/other/cifuzz.yaml
> +#build-command: "make my_fuzz_test"
thanks, fixed

2022-10-12 10:27 UTC, adombeck commented on examples/cmake/README.md
> +You should see two findings, an undefined behavior and a heap buffer
Right. In that case, I'm not sure if it makes sense to mention the `recover-ubsan` in the README at all, it seems to me like we would have to explain too many things that are not really relevant for the user at the point they want to try out the example project.

2022-10-12 10:42 UTC, jochil commented on examples/cmake/README.md
> +You should see two findings, an undefined behavior and a heap buffer
I agree... it might be to specific/advanced for users having their first contact with fuzzing

2022-10-12 11:18 UTC, adombeck commented on examples/cmake/README.md
> +You should see two findings, an undefined behavior and a heap buffer
I removed the commit which updated the READMEs

2022-10-12 11:26 UTC, jochil approved these changes

2022-10-12 14:51 UTC, merged