Print basic fuzzing metrics
CodeIntelligenceTesting/cifuzz pull request #46
Opened 2022-05-31 19:05 UTC by adombeck

This doesn't pretty-print findings yet, those are still printed as JSON.

2022-06-01 07:30 UTC, fmeum commented on internal/cmd/run/metrics/metrics.go
> +	lastNewCoverageDuration := time.Second * time.Duration(metrics.SecondsSinceLastFeature)
I'm not a fan of calling the features count "coverage" since that usually means something else. We could brainstorm other terms. I start to like a simple "progress" in this place.

2022-06-01 07:30 UTC, fmeum commented on internal/cmd/run/metrics/metrics.go
> +	p.averageExecs = (p.numMetrics*p.averageExecs + metrics.ExecutionsPerSecond) / (p.numMetrics + 1)
`p.numMetrics * p.averageExecs` could potentially overflow on long & fast fuzzing runs. You could probably use [this trick](https://nullbuffer.com/articles/welford_algorithm.html) to prevent that.

2022-06-01 07:30 UTC, fmeum commented on internal/cmd/run/run.go
> +	// TODO: Should we include the build time in the "Ran for X" time
I would say only the fuzzing time. Printing and indicating build times would be the job of the build system, whose output we still print (right?)

2022-06-01 07:30 UTC, fmeum commented on internal/cmd/run/run.go
> +				return nil
Is the libfuzzer behavior to not recurse into directories? I wasn't aware of this and implemented recursive traversals in the replayer.

2022-06-01 07:32 UTC, fmeum commented on internal/cmd/run/metrics/metrics.go
> +	p.averageExecs = (p.numMetrics*p.averageExecs + metrics.ExecutionsPerSecond) / (p.numMetrics + 1)
That said, I think we want to make this a float/double even if we don't print it as such.

2022-06-01 10:46 UTC, adombeck commented on internal/cmd/run/metrics/metrics.go
> +	lastNewCoverageDuration := time.Second * time.Duration(metrics.SecondsSinceLastFeature)
I called it that because that's the name of the report field in our core repo (see the JSON name of the field: https://github.com/CodeIntelligenceTesting/cifuzz/blob/CLI-171-print-metrics/pkg/report/report.go#L49-L49).

I'm also unhappy with this naming. When the user runs cifuzz with `--verbose`, the libFuzzer output is printed as well, which continuously prints its stats including `cov:` and `ft:`, and right below those lines we print our own metrics where `coverage:` doesn't match the `cov:` from libfuzzer but the `ft:`, which is obviously strange.

"progress" is better but to me it sounds a bit as if there was a certain value which must be reached to finish the fuzzing.

2022-06-01 11:44 UTC, adombeck commented on internal/cmd/run/metrics/metrics.go
> +	p.averageExecs = (p.numMetrics*p.averageExecs + metrics.ExecutionsPerSecond) / (p.numMetrics + 1)
Good catch! I'm now calculating the average similar to the algorithm you linked and am using a float64 for the calculation. Please take a look.

2022-06-01 12:11 UTC, adombeck commented on internal/cmd/run/run.go
> +	// TODO: Should we include the build time in the "Ran for X" time
> Printing and indicating build times would be the job of the build system, whose output we still print (right?)

Agreed, and yes, we still print the output of the build system

2022-06-01 12:11 UTC, adombeck commented on internal/cmd/run/run.go
> +	// TODO: Should we include the build time in the "Ran for X" time
Done

2022-06-01 12:12 UTC, adombeck commented on internal/cmd/run/run.go
> +				return nil
`filepath.WalkDir` does recurse into directories (same as libFuzzer)

2022-06-01 18:28 UTC, adombeck commented on internal/cmd/run/metrics/metrics.go
> +	p.averageExecs = (p.numMetrics*p.averageExecs + metrics.ExecutionsPerSecond) / (p.numMetrics + 1)
Updated as per our discussion

2022-06-02 07:18 UTC, fmeum commented on internal/cmd/run/metrics/metrics.go
> +	p.averageExecs += (float64(metrics.ExecutionsPerSecond) - p.averageExecs) / float64(p.numMetrics+1)
What I missed on the first pass: This method of calculating the overall average executions/s so far seems flawed as the duration and number of executions between two metrics reports varies. As a result, a simple average doesn't assign the correct weights to the individual data points and, more concretely, would probably always overestimate the true avg exec/s as there tend to be both more executions/s and more metric reports at the beginning of a fuzzing run.

How about we instead track the total number of executions in an uint64 and then compute the average exec/s by dividing by `duration` below?

2022-06-07 18:23 UTC, fmeum commented on internal/cmd/run/metrics/metrics.go
> +	p.averageExecs += (float64(metrics.ExecutionsPerSecond) - p.averageExecs) / float64(p.numMetrics+1)
Thinking about this again: Couldn't we just record the time of the first and the last metric report and use that as the denominator here rather than the total duration of the fuzzing run? That would give us the correct overall average exec/s as of the last update, which is the best we could possibly do here.

2022-06-08 13:15 UTC, adombeck commented on internal/cmd/run/metrics/metrics.go
> +	p.averageExecs += (float64(metrics.ExecutionsPerSecond) - p.averageExecs) / float64(p.numMetrics+1)
Done

2022-06-08 15:25 UTC, adombeck commented
@fmeum: I pushed the changes I made since your last review as fixup commits to hopefully ease the next round of review. I'll squash those before merging.

2022-06-08 22:07 UTC, fmeum approved these changes

2022-06-09 18:09 UTC, adombeck commented
@fmeum: Sorry, have to ask for another review. I pushed 5 more commits which improve formatting and finally (or so I hope) fix the spinner printer when used in verbose mode.

2022-06-10 06:44 UTC, fmeum approved these changes

2022-06-10 06:44 UTC, fmeum commented on internal/cmd/run/report_handler/report_handler.go
> +	// When --json was used, we don't want anything but JSON output on
Is there any downside to *always* printing to stderr? If I remember correctly, we decided that "structured output to stdout" was indeed the only hard rule we wanted to apply.

2022-06-10 06:44 UTC, fmeum commented on pkg/log/log.go
> +	disableColor = !term.IsTerminal(int(os.Stderr.Fd()))
Should the FD used here depend on what we provided to `color.SetOutput`?

2022-06-10 06:44 UTC, fmeum commented on internal/cmd/run/report_handler/report_handler.go
> +			bytes, err := prettyjson.Marshal(r)
Looked great in the demo!

2022-06-10 06:44 UTC, fmeum commented on pkg/parser/libfuzzer/libfuzzer_parser.go
> +			secondsSinceLastFeature = 0
Why is this branch needed?

2022-06-10 06:44 UTC, fmeum commented on internal/cmd/run/metrics/updating_printer.go
> +		pterm.LightYellow(time.Since(p.startedAt).Truncate(time.Second).String()),
I noticed this during the demo: Does this ensure that "last new path" will now always be <= "execution time"?

2022-06-10 06:44 UTC, fmeum commented on util/ptermutil/ptermutil.go
> +	buf := append(oldBuf, p...)
I find it slightly confusing to have three different `buf`-like variables here. Couldn't we keep `len(w.buf)` in `oldBufLen`, set `w.buf = append(w.buf, p...)` and then `w.buf = []byte{}` after the `fmt.Fprint` call? That would fit my mental model of "clearing the buffer after the write" better.

2022-06-10 06:44 UTC, fmeum commented on util/ptermutil/ptermutil.go
> +	// To ensure that after the write, the spinner printer has a new
Great fix, thanks for digging this deep!

2022-06-10 08:44 UTC, jochil commented on pkg/parser/libfuzzer/libfuzzer_parser.go
> +		`#(?P<total_execs>\d+)\s(?P<status>.*)\scov:\s(?P<edges>\d+)\sft:\s(?P<features>\d+)\scorp:\s(?P<corpus_size>\d+)/.*exec/s:\s(?P<executions_per_second>\d+)\s`)
Only a personal preference: For more complicated regex I like to have examples of targeted strings as a comment.
Helps to understand the regex way faster

2022-06-10 08:52 UTC, jochil requested changes
Basically all new files are without any unit test (`line_printer.go`, `metrics.go`, `updating_printer.go`, `report_handler.go`, `ptermutil.go`

2022-06-10 09:37 UTC, adombeck commented on pkg/log/log.go
> +	disableColor = !term.IsTerminal(int(os.Stderr.Fd()))
No, the log package doesn't depend on `color.SetOutput` in the current implementation, it always prints to stderr, see https://github.com/CodeIntelligenceTesting/cifuzz/blob/CLI-171-print-metrics/pkg/log/log.go#L48-L48.

2022-06-10 09:38 UTC, adombeck commented on internal/cmd/run/report_handler/report_handler.go
> +			bytes, err := prettyjson.Marshal(r)
Thanks :)

2022-06-10 09:43 UTC, adombeck commented on pkg/parser/libfuzzer/libfuzzer_parser.go
> +			secondsSinceLastFeature = 0
IIUC, when `p.lastNewFeatureTime` was not set yet, `now.Sub(p.lastNewFeatureTime)` equals `now`, so we would set `secondsSinceLastFeature` to the number of seconds since epoch. But the previous code, `now.Unix() - p.lastNewFeatureTime.Unix()`, should have the same issue and I'm a bit confused why we didn't notice it before.

2022-06-10 09:45 UTC, adombeck commented on internal/cmd/run/metrics/updating_printer.go
> +		pterm.LightYellow(time.Since(p.startedAt).Truncate(time.Second).String()),
That was the goal of this change and in my tests it worked

2022-06-10 10:04 UTC, adombeck commented on util/ptermutil/ptermutil.go
> +	buf := append(oldBuf, p...)
Ah yes, forgot to clean up that mess. Thanks, I implemented your suggestion

2022-06-10 11:26 UTC, fmeum commented on internal/cmd/run/report_handler/report_handler.go
> +	// When --json was used, we don't want anything but JSON output on
Preserving that property makes sense. We should keep the added complexity in mind if we plan future changes in this area though.

2022-06-10 12:00 UTC, adombeck commented on pkg/parser/libfuzzer/libfuzzer_parser.go
> +			secondsSinceLastFeature = 0
I changed this to
```go
var secondsSinceLastFeature uint64
if !p.lastNewFeatureTime.IsZero() {
    secondsSinceLastFeature = uint64(now.Sub(p.lastNewFeatureTime).Truncate(time.Second).Seconds())
}
```
and am now doing the same below for `secondsSinceLastEdge`.

2022-06-10 16:07 UTC, adombeck commented
> Basically all new files are without any unit test (line_printer.go, metrics.go, updating_printer.go, report_handler.go, ptermutil.go)
Also internal/cmd/run/run.go has a lot of changes but no updates to the test

I added tests for the report handler. There I'm also testing the line printer - the updating printer is hard to test and I don't think it's worth the effort.

2022-06-12 13:04 UTC, jochil approved these changes

2022-06-13 09:13 UTC, merged