cmd/run: Support passing flags to cmake
CodeIntelligenceTesting/cifuzz pull request #520
Opened 2022-12-08 14:40 UTC by florianGla

2022-12-08 14:59 UTC, fmeum requested changes

2022-12-08 14:59 UTC, fmeum commented on internal/build/cmake/cmake.go
> +	args = append(args, b.Args...)
CMake cache variables are cached in the build directory, so users may get unexpected results if they vary arguments. We can either:

1. hash the args and add the hash to the name of the build directory or
2. research how we can force an override of the cache variables.

2022-12-09 10:46 UTC, florianGla commented on internal/build/cmake/cmake.go
> +	args = append(args, b.Args...)
I implemented the first variant.

2022-12-09 11:50 UTC, fmeum requested changes

2022-12-09 11:50 UTC, fmeum commented on internal/build/cmake/cmake.go
> +	buildDir := fmt.Sprintf("%s-%s", sanitizersSegment, hash)
Let us append the hash only if `b.Args` isn't empty so that common use cases don't add it.

2022-12-09 11:50 UTC, fmeum commented on internal/build/cmake/cmake.go
> +	sum := sha1.Sum(bytes)
Don't use SHA-1 (or MD5) for anything anymore. If security is a concern or performance is not, use SHA-256/512. If it's certain that security is no concern (such as in this case) and performance is important (it isn't in this case), use [xxHash](https://github.com/cespare/xxhash).

2022-12-09 11:50 UTC, fmeum commented on internal/build/cmake/cmake.go
> +		bytes = append(bytes, []byte(arg)...)
This scheme has a subtle bug that is commonly made when hashing collections: `[]string{"foo", "bar"}` and `[]string{"foobar"}` will hash to the same value.

Instead, use `sha256.New()` to get an `io.Writer` and, for each arg, use `binary.Write` to first write the length of the argument followed by the bytes of the argument.

2022-12-13 15:59 UTC, fmeum approved these changes

2022-12-13 17:15 UTC, merged