Remove mentions of AFL + refactoring
CodeIntelligenceTesting/cifuzz pull request #532
Opened 2022-12-13 20:49 UTC by adombeck

We don't support AFL and it's not on the roadmap to support it, so this PR contains the following changes:
* Remove all mentions of AFL in user-facing docs.
* Make engine non-configurable and always use "libfuzzer" as the value

Also contains some minor refactoring of the bundler package.

2022-12-14 09:30 UTC, jochil approved these changes

2022-12-14 11:30 UTC, adombeck commented
> Maybe updating the cifuzz.yamls in the example projects, too?

Right, forgot that. Done.

2022-12-14 16:00 UTC, florianGla requested changes
If think you can also remove this comment in pflag.go:
`// TODO(afl): Also link to https://aflplus.plus/docs/fuzzing_in_depth/#a-collecting-inputs`

2022-12-15 10:53 UTC, adombeck commented
> If think you can also remove this comment in pflag.go: `// TODO(afl): Also link to https://aflplus.plus/docs/fuzzing_in_depth/#a-collecting-inputs`

I left the `TODO(afl)` comments on purpose because those are still valid TODOs for when we actually work on AFL support (which is what the `(afl)` is supposed to mean).

2022-12-19 10:59 UTC, florianGla approved these changes

2022-12-19 11:28 UTC, merged