Kotlin fuzz test completion
CodeIntelligenceTesting/cifuzz pull request #588
Opened 2023-01-25 15:15 UTC by florianGla

Provide fuzz test completion for kotlin projects

2023-01-26 14:34 UTC, MarkusZoppelt approved these changes
lgtm

2023-01-26 18:58 UTC, jochil requested changes
I might be wrong but I think the whole assumption that a project with a kotllin based gradle setup has to be a kotlin only project is wrong. 

You can have it all ways, like a java project with a kotlin based gradle or a kotlin project with a grovy based gradle... and so on

2023-01-26 18:58 UTC, jochil commented on internal/bundler/jazzer_bundler.go
> +		kts, err := fileutil.Exists(filepath.Join(b.opts.ProjectDir, "build.gradle.kts"))
I think you can also use a kotlin based gradle setup in a Java project without any kotlin. So the assumption that a project with a `build.gradle.kts` is always a kotlin project might be wrong

2023-01-26 18:58 UTC, jochil commented on internal/bundler/jazzer_bundler.go
> +		}
I am also not sure if this is a correct assumption...IIRC you can mix them, having Kotlin classes next to java classes

2023-01-31 12:29 UTC, MarkusZoppelt commented on internal/bundler/jazzer_bundler.go
> +		kts, err := fileutil.Exists(filepath.Join(b.opts.ProjectDir, "build.gradle.kts"))
I removed this check and now add/collect both (Java + Kotlin) fuzztests when using Gradle.

2023-01-31 13:25 UTC, jochil commented on internal/bundler/jazzer_bundler.go
> +		kts, err := fileutil.Exists(filepath.Join(b.opts.ProjectDir, "build.gradle.kts"))
why gradle? This should be true for maven as well

2023-01-31 14:19 UTC, MarkusZoppelt commented on internal/bundler/jazzer_bundler.go
> +		kts, err := fileutil.Exists(filepath.Join(b.opts.ProjectDir, "build.gradle.kts"))
Changed. We will now collect all fuzztests

2023-02-01 19:25 UTC, jochil commented on internal/bundler/jazzer_bundler.go
> +		tests, err = listFuzzTests(config.KOTLIN, b.opts.ProjectDir)
what do you think about just having one `listFuzzTests(config.JVM...` instead of two code blocks

2023-02-01 19:25 UTC, jochil commented on internal/config/config.go
> +func DetermineGradleTestType(projectDir string) (FuzzTestType, error) {
I think `TestType` is somehow misleading... IMO it has nothing to do with the tests.
So gradle itself calls it Groovy DSL/Kotlin DSL or "Gradle Build Language"... the function name should reflect this

2023-02-01 19:25 UTC, jochil commented on internal/config/config.go
> +	return JAVA, nil
This should be `GROOVY`

2023-02-01 19:25 UTC, jochil commented on internal/config/config.go
> +}
If we check for `JVM` as a test type we can get rid of this function

2023-02-01 19:25 UTC, jochil commented on internal/completion/fuzz_test_completion.go
> +		validFuzzTests = append(validFuzzTests, tests...)
same here... This could be one block if we just check for `JVM` instead of Java and kotlin

2023-02-02 12:48 UTC, MarkusZoppelt commented on internal/config/config.go
> +func DetermineGradleTestType(projectDir string) (FuzzTestType, error) {
Renamed

2023-02-02 14:01 UTC, MarkusZoppelt commented on internal/bundler/jazzer_bundler.go
> +		tests, err = listFuzzTests(config.KOTLIN, b.opts.ProjectDir)
Should be simpler now after my latest refactor commit.

2023-02-03 08:23 UTC, jochil commented on internal/cmdutils/jazzer.go
> +
I would use a `map[string]string` for this, then you can just iterate over the map with `k, v := range` and don't have to access a second slice by `i`

2023-02-03 08:32 UTC, jochil commented on internal/cmdutils/jazzer.go
> +	err := filepath.Walk(dir, func(path string, info os.FileInfo, err error) error {
I think this can be a glob search too... might be more straightforward than the `filepath.Walk`

2023-02-03 08:34 UTC, jochil commented on internal/config/config.go
> +	kts, err := fileutil.Exists(filepath.Join(projectDir, "build.gradle.kts"))
There can be multi-project setups in grade where the project root does not contain a `build.gradle` but a `settings.gradle(.kts)`

2023-02-03 12:10 UTC, jochil commented on internal/config/config.go
> +	kts, err := fileutil.Exists(filepath.Join(projectDir, "build.gradle.kts"))
I will take care of this in another fix/pr

2023-02-03 12:10 UTC, jochil approved these changes

2023-02-03 21:53 UTC, merged