CLI 785 add finding details
CodeIntelligenceTesting/cifuzz pull request #613
Opened 2023-02-07 14:57 UTC by MarkusZoppelt

- feat(api): add error_details to api package
- feat: add error details to findings

2023-02-08 18:48 UTC, jochil requested changes
IMO the whole adding of the information should happen in another place. When the application detects a finding we should immediately use the information from `error.json`  and not just before we upload it

2023-02-08 18:48 UTC, jochil commented on internal/api/error_details.go
> +	}
It's temporary but you can also use `fileutil.Exists`

2023-02-08 18:48 UTC, jochil commented on internal/api/error_details.go
> +type EDetails struct {
The name is confusing, first because of the existence of `ErrorDetail` and `ErrorDetails` and Second because it is plural but it is basically a smaller version of `ErrorDetail` which is singular... whats about `ExternalDetail`?

2023-02-08 18:48 UTC, jochil commented on internal/api/error_details.go
> +func (errorDetails ErrorDetails) GetErrorDetailFromID(id string) *ErrorDetail {
What do you think about `FindByName` and `FindByID`?

2023-02-08 18:48 UTC, jochil commented on internal/api/finding.go
> +	Description string `json:"description,omitempty"`
This are basically the same structs as `ErrorDetail` and `EDetails`... why are we not reusing them? This seems to be prone to forgot updating both structs when new fields where added

2023-02-08 18:48 UTC, jochil commented on internal/api/finding.go
> +func constructDetails(errorDetails ErrorDetails, finding *finding.Finding) MoreDetails {
1. As mentioned before, I am not sure if we should have or need both structs
2. the `MoreDetails` return should be a pointer
3. can be a `New` function

2023-02-08 21:43 UTC, MarkusZoppelt commented on internal/api/error_details.go
> +type EDetails struct {
I like `ExternalDetail` - thank you for the suggestion!

2023-02-08 21:50 UTC, MarkusZoppelt commented on internal/api/finding.go
> +	Description string `json:"description,omitempty"`
Didn't catch that. Thx!

2023-02-09 13:58 UTC, MarkusZoppelt commented on internal/api/finding.go
> +func constructDetails(errorDetails ErrorDetails, finding *finding.Finding) MoreDetails {
I refactored the code, so that finding details are now directly added before saved to disk. This happens in [report_handler.go](https://github.com/CodeIntelligenceTesting/cifuzz/pull/613/files#diff-89d321fb00b8c9f72672304282cd096ef5d0f3f186767e6a867e980244a62fbe)

2023-02-13 16:47 UTC, MarkusZoppelt commented
@jochil I added the changes you requested. Would you please review again? Thank you!

2023-02-14 07:58 UTC, jochil reviewed
thanks for the adjustments... IMO it would help for the reviewing to squash/revise these adjustments into the original commits

2023-02-14 07:58 UTC, jochil commented on pkg/finding/finding.go
> +		if strings.EqualFold(d.Name, f.ShortDescriptionColumns()[0]) {
can you add a TODO here to make it clear that we have to optimize the matching of the errors?

2023-02-14 07:58 UTC, jochil commented on pkg/finding/finding.go
> +		}
Maybe I am missing something, but this whole block seems unnecessary and prone to making mistakes when changing it. Why not just `moreDetails = details`? It is basically the same struct, why duplicating it by hand?

2023-02-14 07:58 UTC, jochil commented on pkg/finding/finding.go
> +	if details != nil {
WDYT about an else case, informing about a finding that is not part of our `error.json`... might be interesting for the user and us as well

2023-02-14 07:58 UTC, jochil commented on pkg/finding/finding.go
> +		// if thhe score is still 0, then the finding is not in the
```suggestion
		// if the score is still 0, then the finding is not in the
```

2023-02-14 07:58 UTC, jochil commented on pkg/finding/finding.go
> +		if moreDetails.Severity.Score == 0 {
couldn't this be handle in an else branch of `details != nil`?

2023-02-14 09:24 UTC, MarkusZoppelt commented on pkg/finding/finding.go
> +	if details != nil {
I added a `log.Info` statement

2023-02-14 09:26 UTC, MarkusZoppelt commented on pkg/finding/finding.go
> +		}
Oh wow, you're right. I changed the type of the details struct earlier so they weren't directly compatible.

Now they are:
`moreDetails = *details`

2023-02-14 09:27 UTC, MarkusZoppelt commented on pkg/finding/finding.go
> +		if moreDetails.Severity.Score == 0 {
Done

2023-02-15 11:09 UTC, jochil approved these changes

2023-02-15 11:26 UTC, merged