Cli 916 token creation messaging
CodeIntelligenceTesting/cifuzz pull request #651
Opened 2023-02-28 11:59 UTC by HenrichN

### Motivation & Context
Add A/B testing capabilities for messaging while connecting to our SaaS.

### Description
Different messages are included and depending on the message shown different UTM parameters are set for the token creation URL

2023-03-01 09:35 UTC, MarkusZoppelt requested changes

2023-03-01 09:35 UTC, MarkusZoppelt commented on internal/cmd/run/run.go
> +
Thank you for contribution!

We usually use backticks (`) with linebreaks after < 80 chars for long strings that we show to users so they get printed on smaller terminal sessions.

E.g., long string messages should look like this (note no tabs after newlines):

```go
	messageA := fmt.Sprintf(`Do you want to persist your findings?
Authenticate with the CI Fuzz Server %s to get more insights.`, server)
	
    messageB := `Code Intelligence provides you a full history for all your findings and allows
you to postpone work on findings and completely ignore them to keep the output
clean and focused.
[...]
```

However, I propose that we store the messages in a list. That way, we get better readability and can access the messages easily by index number coming from the number generator:

```suggestion
	messages := []string{
		fmt.Sprintf(`Do you want to persist your findings?
Authenticate with the CI Fuzz Server %s to get more insights.`, server),

		`Code Intelligence provides you a full history for all your findings and allows
you to postpone work on findings and completely ignore them to keep the output
clean and focused.

With a free authentication you receive detailed information and solution tips for
each findings in your console.
All your finding data stay only with us at Code Intelligence and will never be shared.
	
Do you want to continue with authentication now?`,

	}

```

Later: e.g.:

```go
n := computeStablePseudoRandomNumber()
log.Notef(messages[n])
```

2023-03-01 09:35 UTC, MarkusZoppelt commented on internal/cmd/run/run.go
> +	}
With the messages list (map?), maybe this can also be removed to a single line where you access the item directly.

2023-03-01 09:35 UTC, MarkusZoppelt commented on internal/cmd/run/run.go
> +	}
Not a fan of recovering here. In the (highly unlikely) case that this should fail, we should handle and report the error to the caller.

2023-03-01 09:35 UTC, MarkusZoppelt commented on internal/cmd/run/run.go
> +	}
see other comment

2023-03-01 09:35 UTC, MarkusZoppelt commented on internal/cmd/run/run.go
> +	}
Maybe we can change this to a modulo check, e.g. `something % len(messages)`.

That way, we can handle more than two messages.

2023-03-01 09:35 UTC, MarkusZoppelt commented on internal/cmd/run/run.go
> +func computeStablePseudoRandomNumber() int {
The name of this function in convoluted and contradictory.

How about `pickNumberForMessagingIndex`?

2023-03-01 09:46 UTC, jochil reviewed
What do you think about another approach: Instead of distributing the functionality over multiple places we can have a package that assigns the user to a group (and saves it internally) and then asking the package for messages and additional url params?
It might be less messy if we continue with this kind of stuff

2023-03-01 09:46 UTC, jochil commented on internal/cmd/run/run.go
> +func showServerConnectionMessage(server string) *url.Values {
I think the `showServerConnectionMessage` and `computeStablePseudoRandomNumber` functions would be better placed in a separate package... as they might be used in other commands and for not polluting the run command even more. WDYT about `dialog` or `messaging`

2023-03-02 09:08 UTC, MarkusZoppelt approved these changes

2023-03-02 09:29 UTC, jochil commented on pkg/messaging/messaging.go
> +	}
can we put this in one struct to not rely on some indexes being in the right order? Something like
```
[]struct{
  message string
  urlParams []url.Values
}{
{...},
{...}
}
```

2023-03-02 09:29 UTC, jochil commented on pkg/messaging/messaging.go
> +func PickNumberForMessagingIndex(numberOfMessages int) (int, error) {
can be private as it isn't use outside the packge

2023-03-02 14:15 UTC, jochil approved these changes

2023-03-03 06:39 UTC, merged