fix: add undefined behavior to errorid matchers
CodeIntelligenceTesting/cifuzz pull request #747
Opened 2023-04-14 11:15 UTC by MarkusZoppelt

### Motivation & Context
Undefined behaviors were not picked up consistently and matched with error IDs, e.g., in the `cmake` example:

```
⚠️ unable to find matching error id for given finding: undefined behavior: shift exponent 32 is too large for 32-bit type 'int'
```

Libfuzzer output was:

```
explore_me.cpp:13:11: runtime error: shift exponent 32 is too large for 32-bit type 'int'
```

### Description

Added "undefined behavior" to error ID matchers.

2023-04-14 11:46 UTC, jochil commented on pkg/parser/errorid/errorid.go
> +		id:         "undefined behavior",
```suggestion
		id:         "undefined_behavior",
```
all the other IDs are like this

2023-04-14 11:48 UTC, jochil requested changes
can you please update the package unit tests and the error integration tests with a matching example?

2023-04-14 11:48 UTC, jochil commented on pkg/parser/errorid/errorid.go
> +		regexs:     []*regexp.Regexp{regexp.MustCompile(`undefined behaviou?r: .*`)},
It is not necessary to match for substrings and regex if they are doing essential the same

2023-04-14 12:41 UTC, jochil commented on pkg/parser/errorid/errorid.go
> +	},
the strings we are parsing are coming from our libfuzzer parser, which usually works on the line above the stacktrace... so in this specific case on something like `runtime error: shift exponent 32 is too large for 32-bit type 'int'`... you can take a look at the `out-of-bounds` error, which is also a undefined behavior bug. I have the impression that just looking for `undefined behavior` is a little bit to generic, espeically when we have a specific entry for invalid shifts in our `error_details.json`: https://gitlab.code-intelligence.com/code-intelligence/core/-/blob/master/pkg/fuzzing/error_details/error-details.json#L281

2023-04-14 13:35 UTC, MarkusZoppelt commented on pkg/parser/errorid/errorid.go
> +	},
I added a specific `shift_exponent` error check and leave the "generic" `undefined_behavior` check there, just in case.

2023-04-17 10:46 UTC, MarkusZoppelt commented on pkg/parser/errorid/errorid.go
> +	},
Would you rather remove the undefined behavior check completely and only check for exact matches?

2023-04-17 12:12 UTC, MarkusZoppelt commented on pkg/parser/errorid/errorid.go
> +	},
I removed the check. We can add it back if there is a clear need for it.

2023-04-17 13:55 UTC, jochil approved these changes
lgtm... thanks

2023-04-17 13:55 UTC, jochil commented on pkg/parser/errorid/errorid.go
> +	},
I am fine with removing it for now.

2023-04-17 14:12 UTC, merged