style: adding yaml formatter
CodeIntelligenceTesting/cifuzz pull request #865
Opened 2023-06-23 18:17 UTC by jochil

... because we don't have one by now

2023-06-24 08:57 UTC, MarkusZoppelt requested changes
This change deleted all content from our `**/cifuzz.yaml` files.
(I assume because they only contain comments and nothing else?)

2023-06-26 10:03 UTC, jochil commented
> This change deleted all content from our `**/cifuzz.yaml` files. (I assume because they only contain comments and nothing else?)

:facepalm: I will take a look if there is a workaround/flag/... to handle this

2023-06-28 09:52 UTC, jochil commented
I switched to prettier and applied the formatting to all types it supports (md, js, ...).
It's widely used (in the core repo, too) and it should be easy for the IDEs to pick up the config

2023-06-29 07:34 UTC, MarkusZoppelt approved these changes

2023-06-29 08:55 UTC, merged