Init command: arg should override project type detection
CodeIntelligenceTesting/cifuzz pull request #933
Opened 2023-07-20 15:32 UTC by JackuB

It was reported that arguments aren't taking priority, leading to awkward interactions like cifuzz refusing to init in a Node.js folder without the `prerelease` switch:

```terminal
cifuzz on  main [?] via  v1.20.6 via  v18.16.0
❯ cifuzz init java
cifuzz version 1.0.0
cifuzz does not support Node.js projects yet.
```

### Description

CLI-1162

### How to use/reproduce

E2E test case shows the behavior

2023-08-07 10:08 UTC, adombeck requested changes
I expect that the command still fails if the build system which was determined automatically is not supported on the current platform, because we still call `config.ValidateBuildSystem(opts.BuildSystem)` with the `opts.BuildSystem` which was determined automatically. I think we should not call `config.DetermineBuildSystem(opts.Dir)` at all if `opts.testLang` was provided.

2023-08-07 10:10 UTC, adombeck commented
I appreciate the test driven approach but I would prefer it if you would reverse the order of the commits (i.e. having the commit which adds the test come after the commit which fixes the issue), so that the tests pass for each separate commit which is useful for git bisecting.

2023-08-10 11:49 UTC, JackuB commented
> I think we should not call config.DetermineBuildSystem(opts.Dir) at all if opts.testLang was provided.

Wouldn't that complicate the decision process between the maven or gradle init, when user specified `java` as the `testLang`?
This mapping is awkward on its own already. Anyone else wants to chime in?

---

> the tests pass for each separate commit which is useful for git bisecting

Sure, I can swap the commits, but I don't see "tests passing for commits" as something we could enforce going forward 🤔   we do rely on way too many external factors, especially in integration tests.

2023-08-10 12:09 UTC, jochil commented on internal/config/types.go
> +		return BuildSystemMaven
I think Kotlin can be used with gradle as well... or?

2023-08-10 12:09 UTC, jochil commented on internal/config/types.go
> +		return BuildSystemOther
IMO CPP can be used with `cmake` too

2023-08-14 10:31 UTC, adombeck commented
>> I think we should not call config.DetermineBuildSystem(opts.Dir) at all if opts.testLang was provided.

> I moved the validate check to an else branch if testLang is not specified.

Still not really happy with how we handle things in case that that `testLang` is specified. Let's assume a project which has a `node_modules` directory but the user wants to set it up for Java fuzzing with Gradle. They call `cifuzz init java` to avoid that cifuzz handles it as a JavaScript project. Currently, cifuzz still calls `config.DetermineBuildSystem` which returns `BuildSystemNodeJS`. Because the user specified the language, this decision is overwritten in `GetBuildSystemFromTestType` to `BuildSystemMaven` even if the directory contains Gradle files and no `pom.xml`.

When `testLang` is specified, I think we should only try to determine the build system if we support multiple build systems for the  specified language (currently only the case for Java) and then only check for those.

2023-08-15 08:28 UTC, JackuB commented
> Could we just let the user specify the build system directly instead of the language?

I think this is the only solution that will not make us crazy. I will update the PR

2023-08-17 11:30 UTC, MarkusZoppelt commented on internal/cmd/init/init.go
> +				// We validate arg is allowed, thus we can pick from the map
I don't understand this comment

2023-08-17 12:05 UTC, adombeck commented on internal/cmd/init/init.go
> +	"ts":     string(config.BuildSystemNodeJS),
My IDE complains that this is a redundant type conversion

```suggestion
	"cmake":  config.BuildSystemCMake,
	"maven":  config.BuildSystemMaven,
	"gradle": config.BuildSystemGradle,
	"js":     config.BuildSystemNodeJS,
	"ts":     config.BuildSystemNodeJS,
```

2023-08-17 12:09 UTC, adombeck commented on internal/cmd/init/init.go
> +		Use:   fmt.Sprintf("init [%s]", strings.Join(maps.Keys(supportedInitTestTypes), "|")),
Not introduced by this PR but we should sort this slice to have a deterministic usage message. Currently, `cifuzz init --help` prints the possible values in a different order each time it's called.

2023-08-17 12:12 UTC, adombeck commented
I like the solution but we should be aware that it's a breaking change. So if for example users call `cifuzz init cpp` or `cifuzz init java` in a script, that script will fail once they update to the next cifuzz release. If we're fine with that, we should mention it in the release notes.

2023-08-17 12:15 UTC, adombeck commented on internal/cmd/init/init.go
> +				// We validate arg is allowed, thus we can pick from the map
I understand it as: It's fine to use `opts.testLang` as a key of the `supportedInitTestTypes` map here because we validated above that `opts.testLang` is of type `config.FuzzTestType` which means that it's also a valid key of the `supportedInitTestTypes` map. I also think that the comment could be improved to make it more clear.

2023-08-22 11:09 UTC, MarkusZoppelt approved these changes

2023-08-22 11:15 UTC, adombeck commented on internal/cmd/init/init.go
> +				// We validate arg is allowed, thus we can pick from the map
@JackuB Could try to make the comment more clear?

2023-08-25 13:11 UTC, JackuB commented on internal/cmd/init/init.go
> +		Use:   fmt.Sprintf("init [%s]", strings.Join(maps.Keys(supportedInitTestTypes), "|")),
Added a sorting function to ensure ts and js stay next to each other.

2023-08-29 11:04 UTC, merged