feat: wrapcheck linter
CodeIntelligenceTesting/cifuzz pull request #950
Opened 2023-07-31 08:37 UTC by mlsandnerCI

### Motivation/Context

We decided on new guidelines for error handling and one point is to make sure that we add a stack trace to errors returned from external functions or wrap them (which also includes a stack trace) in a helpful error message.

### Description

Added the [wrapcheck](https://github.com/tomarrell/wrapcheck) linter to check that we add stack traces to errors from functions from external packages (e.g. `filepath`, `url`, `os`) and resolved the linter warnings.

I explicitly ignore our own code (see `ignoreSigs` configuration in `.golangci.yaml`) because I think we should decide  on our own if we need to add context.

2023-08-04 13:57 UTC, adombeck requested changes
This linter seems useful!

2023-08-04 13:57 UTC, adombeck commented on internal/api/api.go
> +		return nil, errors.WithStack(err)
`routines.Wait` returns the first non-nil error returned by any of the functions executed via `routines.Go`, so it returns an error defined by us which should already have a stack trace -> let's not add a duplicate stack trace here.

2023-08-04 13:57 UTC, adombeck commented on internal/api/api.go
>  	return &http.Transport{DialContext: dialContext}
Adding a stack trace here **could** have unexpected side effects because this error is being returned to a function in an external package (the `http` package). I don't expect that the `http` package has special handling for errors returned from the `dialer` package though (and if so, it should use `errors.As` or `errors.Is` which would automatically unwrap the error), so it should be fine.

2023-08-07 06:46 UTC, mlsandnerCI commented on internal/api/api.go
> +		return nil, errors.WithStack(err)
Cool, thanks for the explanation!

2023-08-07 09:48 UTC, adombeck approved these changes

2023-08-08 07:54 UTC, merged