fix(errors): handle all error types correctly in root
CodeIntelligenceTesting/cifuzz pull request #991
Opened 2023-08-17 12:57 UTC by mlsandnerCI

### Motivation/Context

Usage errors were falsely printed with a support message indicating to run the command in verbose mode.

### Description

Refactored the if-clauses in the root command handling the errors to a switch/case to make sure that errors only get printed once. 

In case of the usage error mentioned in the ticket, the error did not get printed at all in the `IncorrectUsageError` handling, only the help message and then it was handled again as "not a `SilentError`" where the error message with the support message + stack trace was printed.

Handling of `ExecError` and `APIError` also got moved to the root command, the stack trace will be printed in verbose mode. 

Edit: The support message got removed.

#### Some error messages for reference
Old `ExecError` message in verbose:
<img width="1456" alt="execErr_old" src="https://github.com/CodeIntelligenceTesting/cifuzz/assets/112617007/4180a016-883e-47b4-bfaf-0cd285269962">

New `ExecError` message:
<img width="1461" alt="Bildschirmfoto 2023-08-17 um 14 26 34" src="https://github.com/CodeIntelligenceTesting/cifuzz/assets/112617007/705101e1-5fef-4d0b-9289-d520e80bbeb9">
<img width="1461" alt="Bildschirmfoto 2023-08-17 um 14 21 41" src="https://github.com/CodeIntelligenceTesting/cifuzz/assets/112617007/838d6ab5-7802-488d-b190-88be70e9793c"> 
Edit: Stacktrace is now gray and there is no support message anymore.

`IncorrectUsageError` message, wrong arguments:
<img width="1028" alt="usageErr_new" src="https://github.com/CodeIntelligenceTesting/cifuzz/assets/112617007/fb4aa599-7537-41ba-b02b-39bf09965c63">

`IncorrectUsageError` message, not a cifuzz project:
<img width="1011" alt="Bildschirmfoto 2023-08-17 um 14 45 51" src="https://github.com/CodeIntelligenceTesting/cifuzz/assets/112617007/525625ed-25cb-474c-bade-72eb205ba56e">

2023-08-17 13:49 UTC, adombeck commented
> New ExecError message:
> ![image](https://github.com/CodeIntelligenceTesting/cifuzz/assets/18482300/f403122f-c6e3-481e-8fa1-f31cfde0567e)

I find the "More information can be acquired running the command in verbose mode (--verbose)" confusing here. It as if the user could get some useful information when re-running with `--verbose`, but it will only show them the stack trace, which is not useful information for the user. The reason we print a stack trace in verbose mode is to make things easier for us developers, not because it's useful information for the user.

2023-08-18 07:06 UTC, mlsandnerCI commented
For a `ExecError` the user would get the command that failed in verbose mode, wouldn't that classify as more information? 🤔

2023-08-18 07:25 UTC, mlsandnerCI commented
<img width="1451" alt="Bildschirmfoto 2023-08-18 um 09 24 26" src="https://github.com/CodeIntelligenceTesting/cifuzz/assets/112617007/5592b9e5-a12e-4563-a531-324aa9d5fcc7">

I like the change to grey and I removed the support message for all cases.

2023-08-18 10:33 UTC, adombeck commented
This looks good!

2023-08-18 10:47 UTC, adombeck commented on internal/cmd/root/root.go
> +		// Configure error formatting because we can't use the log package here
Why can't we use the log package here?

2023-08-18 10:54 UTC, adombeck commented on internal/cmd/root/root.go
> +		switch {
Using `switch` here instead of multiple `if` statements has the effect that only the first `case` which matches is executed. The error types are not mutually exclusive though, e.g. it's possible that an error is wrapped as both an `ExecError` and a `CouldBeSandboxError`. Either we add `fallthrough` statements to each case or we revert this back to use `if` statements.

2023-08-18 10:55 UTC, adombeck commented on internal/cmd/root/root.go
> +		switch {
We also have to make sure that the error is not printed twice in these cases.

2023-08-18 12:03 UTC, mlsandnerCI commented on internal/cmd/root/root.go
> +		switch {
I did not know that this case exists, thanks for pointing it out. I will adjust the code.

2023-08-22 07:43 UTC, mlsandnerCI commented on internal/cmd/root/root.go
> +		// Configure error formatting because we can't use the log package here
`log.Error()` would always print a stack trace in verbose mode and not the stack trace of the root error but of the last one that wrapped it. 
And we didn't use it before I refactored it, I'm assuming there is another reason why we decided not to use it here.

2023-08-22 07:44 UTC, mlsandnerCI commented on internal/cmd/root/root.go
> +		switch {
I updated the code but I'm unsure if this is okay now. Could you recheck?

2023-08-22 07:47 UTC, mlsandnerCI commented
It is not necessary to have the distinction of the `execError` and `apiError` in the if clause that also checks `!silentError` but I thought it would be more explicit this way and easier to refactor if we do want to change how we handle them at some point.

2023-08-23 09:31 UTC, adombeck requested changes

2023-08-23 09:31 UTC, adombeck commented on internal/cmd/root/root.go
>  running it without sandboxing:
We want to print this note after the error message, so this if block should be moved below the one which prints non-silent errors.

It (accidentally) worked as expected before, because we handled all errors which we wrapped as `CouldBeSandboxError` on an upper layer and returned a `SilentError`.

2023-08-23 09:31 UTC, adombeck commented on internal/cmd/root/root.go
>  running it without sandboxing:
While testing this, I noticed that we didn't print the note for the `CouldBeSandboxError` returned here: https://github.com/CodeIntelligenceTesting/cifuzz/blob/mlsandnerCI%2FCLI-1189-error-no-stacktrace/internal/cmd/coverage/llvm/llvm.go#L89-L89

I fixed that in a commit which I pushed to this branch, @mlsandnerCI please review that commit.

2023-08-23 09:31 UTC, adombeck commented on internal/cmd/root/root.go
> +			!errors.As(err, &silentErr) {
This has the effect that an `ExecError` or `ApiError` which was wrapped as `SilentError` is still printed. We don't want to print any `SilentError` though, so lets remove the check for `ExecError` and `ApiError` here.

2023-08-23 10:27 UTC, adombeck commented on internal/cmd/root/root.go
> +		// Configure error formatting because we can't use the log package here
> log.Error() would always print a stack trace in verbose mode and not the stack trace of the root error but of the last one that wrapped it.

Ah that's because of the `errors.As(errors.Cause(err), &st)`. Took me a while to understand, a comment would have been helpful there. But I think this behavior is a problem actually: If the original error doesn't have a stack trace, we don't print a stack trace even if `err` does have one. That's the case when we return an error that's wrapped via `errors.WithStack` or `errors.Wrap` but not as any other error (like `ExecError`). To test this, you can for example make the creation of the build dir fail:
```
rm -rf examples/cmake/.cifuzz-build
touch examples/cmake/.cifuzz-build
make install && cifuzz -C examples/cmake run my_fuzz_test -v
```

2023-08-24 13:47 UTC, mlsandnerCI commented on internal/cmd/root/root.go
> +			err = errors.Wrap(err, "Invalid usage")
I would argue that using cifuzz outside of an initialized project is an incorrect usage of cifuzz from the user. I added the "Invalid Usage" message to show the user that this is something they can fix, in this case either changing the directory or running `cifuzz init`. Homebrew does this too and I think it provides value for the user. 

And I do believe that it is easier to read the error message if the "use cifuzz init" solution is separately. The first error message is very long plus it seems more logical to first print the error and then the solution.  

I would prefer to keep it like this. If however this is something you strongly feel about and because this is not a right vs wrong decision but a style decision, I would suggest a voting from the team and see what everyone else thinks?

2023-08-24 13:57 UTC, mlsandnerCI commented on internal/cmd/root/root.go
> +		// Configure error formatting because we can't use the log package here
I wrote a comment but I can elaborate it if needed. 
```
// If running in verbose mode, check if the root error has a
// stacktrace attached and print it (except for usage errors)
```

This was a deliberate decision in the last PR that only the original stack trace gets printed. For example the stack trace pointing to a go routine which returned an error which actually happened somewhere else is useless IMO. If we need a stack trace at the point where the error occurs, we should add it right there.

2023-08-24 14:44 UTC, adombeck commented on internal/cmd/root/root.go
> +		// Configure error formatting because we can't use the log package here
The problem is that if the original error originates in the standard library or a third-party package, it does not have a stack trace. That's why we call `errors.WithStack` or `errors.Wrap` when we get an error from such a package. `errors.Cause(err)` returns the original error from the third-party package, so it strips the stack trace we add and doesn't print any stack trace.

IMO the correct solution is to print the stack trace of `err` instead and ensure that we never add more than one stack trace to an error.

2023-08-24 14:48 UTC, mlsandnerCI commented on internal/cmd/root/root.go
> +		// Configure error formatting because we can't use the log package here
That is true with the librarys/external packages. We can try and see if your solution works out 👍 Wrapping always adds a stack trace that's why I added this part to make sure we print the correct one. If we have a situation where the error does not print the correct stack trace, we can always come back to this and see how we can adjust this.

2023-08-24 15:14 UTC, adombeck commented on internal/cmd/root/root.go
> +		// Configure error formatting because we can't use the log package here
> that's why I added this part to make sure we print the correct one.

Note that the only reason that most of our errors were still printed with a stack trace after that part was implemented is that we wrap most errors with one of our own error types, like `IncorrectUsageError` or `ExecError`, which don't implement the `Cause` method, so `errors.Cause` returns that error instead of the original.

2023-08-24 15:28 UTC, adombeck commented on internal/cmd/root/root.go
> +				_, _ = fmt.Fprint(cmd.ErrOrStderr(), stackTraceStyle.Sprintf("%+v", st.StackTrace()))
The error + stack trace we print here look great now! I think we should use the same style in the `log.Error` package. And if we move the respective code there, we might be able to just call `log.Error` here. What do you think?

2023-08-25 07:30 UTC, mlsandnerCI commented on internal/cmd/root/root.go
> +				_, _ = fmt.Fprint(cmd.ErrOrStderr(), stackTraceStyle.Sprintf("%+v", st.StackTrace()))
Sounds great 👍 Should I add it in this PR?

2023-08-25 10:45 UTC, mlsandnerCI commented on internal/cmd/root/root.go
>  running it without sandboxing:
Can a signal error also be a sandbox error? Because then I would need to remove the os.Exit from that if-clause so that we can still print this error message if it is checked after the non-silent error check 🤔

2023-08-25 10:56 UTC, adombeck commented on internal/cmd/root/root.go
>  running it without sandboxing:
No, we return a `SignalError` when cifuzz catches a terminating signal and a `CouldBeSandboxError` when a command that's executed in Minijail fails. But it's good that you considered that case 👌

2023-08-25 10:56 UTC, mlsandnerCI commented on internal/cmd/root/root.go
> +				_, _ = fmt.Fprint(cmd.ErrOrStderr(), stackTraceStyle.Sprintf("%+v", st.StackTrace()))
The only thing I am struggling now is the IncorrectUsage error. I would like to use log.Error but I don't want to add a check in the function for this special error so we don't print a stack trace and as far as I know there is now way to remove a stack trace from an error. 

Either we never add a stack trace to this kind of error which means I would have to check everywhere that we always initialize the error correctly. This would fit in our guidelines to only add stack traces where we need them but this approach could be error prone if we accidentally use the wrong function and add a stack trace. 

We could also have another function like `SimpleError()` that only prints the error message itself and use that but I don't think that is really an optimal solution. What do you think?

2023-08-25 11:06 UTC, adombeck commented on internal/cmd/root/root.go
> +				_, _ = fmt.Fprint(cmd.ErrOrStderr(), stackTraceStyle.Sprintf("%+v", st.StackTrace()))
Ah yes I see the problem. I think an additional function to print an error without the stack trace makes sense, something like this:

```diff
diff --git a/pkg/log/log.go b/pkg/log/log.go
index 728c0077..e0ba0d01 100644
--- a/pkg/log/log.go
+++ b/pkg/log/log.go
@@ -133,13 +133,17 @@ func Errorf(err error, format string, a ...any) {
 	Error(err, fmt.Sprintf(format, a...))
 }
 
-func Error(err error, a ...any) {
+func printError(err error, withStack bool, a ...any) {
 	// If no message is provided, print the message of the error
 	if len(a) == 0 {
 		a = []any{err.Error()}
 	}
 	log(pterm.Style{pterm.Bold, pterm.FgRed}, "❌ ", a...)
 
+	if !withStack {
+		return
+	}
+
 	type stackTracer interface {
 		StackTrace() errors.StackTrace
 	}
@@ -149,6 +153,14 @@ func Error(err error, a ...any) {
 	}
 }
 
+func Error(err error, a ...any) {
+	printError(err, true, a...)
+}
+
+func ErrorWithoutStack(err error, a ...any) {
+	printError(err, false, a...)
+}
+
 // Infof outputs a regular user message without any highlighting
 func Infof(format string, a ...any) {
 	Info(fmt.Sprintf(format, a...))
```

2023-08-25 11:07 UTC, mlsandnerCI commented on internal/cmd/root/root.go
> +				_, _ = fmt.Fprint(cmd.ErrOrStderr(), stackTraceStyle.Sprintf("%+v", st.StackTrace()))
Cool, thanks for the quick feedback!

2023-08-28 06:50 UTC, mlsandnerCI commented on pkg/log/log.go
> +		Info(fmt.Sprintf("%+v", st.StackTrace()))
I already gave up hope on this because I could not find a way to make this work. I always thought I would have to remove the suffix from the error message which just resulted in weird code, not the prefix from the stack trace. Thanks so much!

2023-08-28 07:07 UTC, mlsandnerCI commented
The `TestError_Verbose` test is failing because it expects the error message to be printed in verbose mode when log.Error() is used with a message (`log.Error(err, "Test")`). 

What is the actual behavior we are expecting? 
Before this refactoring the test worked, because we called `Debug()` to print the stack trace which printed the error message again. So we had the message, then the error message and then the stack trace. Because we now only print the stack trace itself, adding a message when logging the error doesn't result in the error message being printed anymore, only the message itself and then the stack trace. 
But we do want it to be printed, right? I would suggest wrapping the error in the provided message before logging it 🤔

2023-08-28 11:15 UTC, adombeck commented
> But we do want it to be printed, right? I would suggest wrapping the error in the provided message before logging it 🤔

The problem I see with automatically wrapping the error in the provided message in `log.Error` / `log.Errorf` is that the caller can't decide the format of that wrapping. For example, if the provided message is long, we probably want to show the error message on a separate line. If the provided message is short, we want to show it in the format `%s: %s`. Currently, the caller can decide the format, which provides the needed flexibility.

I suggest we keep the current behavior and explain in the function's doc comment that the error message will not be printed unless `err` is the only argument. This should also require fewer adaptions of existing calls to `log.Errorf`, because in most of those we already include `err.Error` in the provided message.

This has consequences for the `ErrorWithoutStack` function: It doesn't make sense to provide it an `err` argument if neither the message nor the stack trace of it is printed. I suggest we rename it and remove the `err` argument.

I already implemented my suggestions and adapted existing calls to `log.Error` and `log.Errorf` to test the feasibility. I'm pushing two commits, please take a look and tell me what you think.

2023-08-28 11:29 UTC, adombeck commented on internal/cmd/root/root.go
> +			err = errors.Wrap(err, "Invalid usage")
We don't want to attach a stack trace here
```suggestion
			err = errors.WithMessage(err, "Invalid usage")
```

2023-08-28 13:45 UTC, mlsandnerCI commented
> > But we do want it to be printed, right? I would suggest wrapping the error in the provided message before logging it 🤔
> 
> The problem I see with automatically wrapping the error in the provided message in `log.Error` / `log.Errorf` is that the caller can't decide the format of that wrapping. For example, if the provided message is long, we probably want to show the error message on a separate line. If the provided message is short, we want to show it in the format `%s: %s`. Currently, the caller can decide the format, which provides the needed flexibility.
> 
> I suggest we keep the current behavior and explain in the function's doc comment that the error message will not be printed unless `err` is the only argument. This should also require fewer adaptions of existing calls to `log.Errorf`, because in most of those we already include `err.Error` in the provided message (which means it would be printed twice if we wrap it with the error message).
> 
> This has consequences for the `ErrorWithoutStack` function: It doesn't make sense to provide it an `err` argument if neither the message nor the stack trace of it is printed. I suggest we rename it and remove the `err` argument.
> 
> To test the feasibility, I already implemented my suggestions and adapted existing calls to `log.Error` and `log.Errorf`. I'm pushing two commits, please take a look and tell me what you think.

I think your solution is good! I only cleaned up the commits and improved two comments.

I really like the outcome of this even if it was a long process, thanks @adombeck 👍

2023-08-28 14:31 UTC, adombeck approved these changes

2023-08-29 11:55 UTC, merged